//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCertificate
    {
        public int CertificateID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CertificateType { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string ValidationCode { get; set; }
        public Nullable<System.DateTime> CertificateIssueDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual tblCertificateType tblCertificateType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
