//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnrollment
    {
        public int EnrollmentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string GRNumber { get; set; }
        public Nullable<System.DateTime> EntrollmentDate { get; set; }
        public Nullable<System.DateTime> EnrollFrom { get; set; }
        public Nullable<System.DateTime> EntrollTo { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsDropOff { get; set; }
        public Nullable<bool> IsDefaulter { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
