//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEnrollment()
        {
            this.tblFees = new HashSet<tblFee>();
        }
    
        public int EnrollmentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string GRNumber { get; set; }
        public Nullable<System.DateTime> EntrollmentDate { get; set; }
        public Nullable<System.DateTime> EnrollFrom { get; set; }
        public Nullable<System.DateTime> EnrollTo { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsDropOff { get; set; }
        public Nullable<bool> IsDefaulter { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> Branch_FK { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCourse tblCourse { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFee> tblFees { get; set; }
    }
}
