//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFee
    {
        public int FeesID { get; set; }
        public Nullable<int> EnrollmentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> FeesType { get; set; }
        public Nullable<System.DateTime> ForMonth { get; set; }
        public Nullable<int> ChargeBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<int> DeleteOn { get; set; }
    
        public virtual tblFeesType tblFeesType { get; set; }
        public virtual tblEnrollment tblEnrollment { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
